---
# tasks file for packaging_server
- name: repo and cache update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: ensure docker packages is present
  apt:
    name: docker.io
    state: present