---
# tasks file for application_server
- name: repo and cache update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: ensure tomcat packages is present
  apt:
    name: tomcat9
    state: present
      