---
- name: application serve configuration
  hosts: tom
  become: yes

  roles:
   - application_server

- name: packaging servver configuration
  hosts: mvn
  become: yes

  roles:
   - packaging_server
   - deploy_app

- name: final deploy_app
  hosts: tom
  become: yes

  roles:
   - deploy_app__to_server